### PR TITLE
Add support to define an endpoint type of VPC; also allow setting oth…

### PR DESCRIPTION
**Pull request by diego-ojeda-binbash**
…er protocols, security policy, host key and certificate

This can be useful if you need to further customize your AWS Transfer server to work on a VPC, either privately or internet-facing. That way you can leverage nice VPC features such as security groups which you can then use for IP whitelisting.

### CODE REVIEW

**Review by lgallard — APPROVED** [review]
LGTM!

**Comment by exequielrafaela** [comment]
Hey @CoryAtTruss @cblkwell @dynamike hope you have some time to check this PR that adds support to several extra aws_transfer_server (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/transfer_server) resource configurations. Such us

*  Define an endpoint type of VPC; also 
* Allow setting other [protocols](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/transfer_server#protocols), 
* Security policy, 
* Host key and 
* ACM certificate.

This can be very useful if you need to further customize your AWS Transfer server to work on a VPC, either privately or publicly (internet-facing). That way you can leverage nice VPC features such as security groups which you can then use for IP whitelisting.

### Example

```terraform
module "sftp_server" {
  source = "github.com/binbashar/terraform-aws-sftp.git?ref=v1.1.0-1"

  name          = "${var.project}-${var.prefix}-customer-files"
  iam_role_name = "sftp-logging-role"

  endpoint_type = var.server_endpoint_type

  # Define server endpoint details when endpoint type is VPC
  endpoint_details = {
    vpc = {
      address_allocation_ids = [aws_eip.sftp_server[0].allocation_id]
      subnet_ids             = [data.terraform_remote_state.vpc.outputs.public_subnets[0]]
      vpc_id                 = data.terraform_remote_state.vpc.outputs.vpc_id
      security_group_ids     = [aws_security_group.sftp_server[0].id]
    }
  }

  protocols = ["FTP", "FTPS"]
  host_key  = var.server_host_key

  tags = local.tags
}
```

Thanks in advance for your time and collaboration.

CC: @binbashar/leverage-ref-architecture-aws-admin @binbashar/leverage-ref-architecture-aws-dev

**Review by esacteksab — APPROVED** [review]
Thank you for the contribution. Apologies it took this long.

**Comment by esacteksab** [comment]
This was released in 1.2 https://github.com/trussworks/terraform-aws-sftp/releases/tag/v1.2.0

**Pull request merged**
